<a href="https://colab.research.google.com/github/laurenkzz/1BI_InteligenciaArtificial/blob/main/Trabalho2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

dados = [
    [18, 1000, 5, "nao"],
    [22, 2000, 10, "nao"],
    [25, 3000, 15, "sim"],
    [30, 4000, 20, "sim"],
    [35, 5000, 25, "sim"],
    [40, 6000, 30, "sim"],
    [20, 1500, 7, "nao"],
    [28, 3500, 18, "sim"],
    [32, 4500, 22, "sim"],
    [24, 2500, 12, "nao"]
]

df = pd.DataFrame(dados, columns=["idade", "renda", "tempo_site", "comprou"])

df["comprou"] = df["comprou"].map({"sim": 1, "nao": 0})

X = df[["idade", "renda", "tempo_site"]]
y = df["comprou"]

# divisão treino/teste
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

# resultados do knn
resultados_knn = []
for k in [1, 3, 5]:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)
    pred = knn.predict(X_test)
    acc = accuracy_score(y_test, pred)
    resultados_knn.append({
        "Modelo": "KNN",
        "Parâmetro": f"k={k}",
        "Acurácia": round(acc, 2)
    })

# resultados da árvore
resultados_tree = []
for depth in [2, 3, 5]:
    tree = DecisionTreeClassifier(max_depth=depth, random_state=42)
    tree.fit(X_train, y_train)
    pred = tree.predict(X_test)
    acc = accuracy_score(y_test, pred)
    resultados_tree.append({
        "Modelo": "Árvore de Decisão",
        "Parâmetro": f"max_depth={depth}",
        "Acurácia": round(acc, 2)
    })


resultados = pd.DataFrame(resultados_knn + resultados_tree)

print("Dataset utilizado:")
display(df)

# exibir resultados
print("Resultados dos modelos:")
display(resultados)

melhor_modelo = resultados.loc[resultados["Acurácia"].idxmax()]
print("Melhor resultado encontrado:")
display(pd.DataFrame([melhor_modelo]))

Dataset utilizado:

   idade  renda  tempo_site  comprou
0     18   1000           5        0
1     22   2000          10        0
2     25   3000          15        1
3     30   4000          20        1
4     35   5000          25        1
5     40   6000          30        1
6     20   1500           7        0
7     28   3500          18        1
8     32   4500          22        1
9     24   2500          12        0

Resultados dos modelos:

              Modelo    Parâmetro  Acurácia
0                KNN          k=1       1.0
1                KNN          k=3       1.0
2                KNN          k=5       1.0
3  Árvore de Decisão  max_depth=2       1.0
4  Árvore de Decisão  max_depth=3       1.0
5  Árvore de Decisão  max_depth=5       1.0

Melhor resultado encontrado:

  Modelo Parâmetro  Acurácia
0    KNN       k=1       1.0